### ISSUE TITLE
这个库适用最新的supabase版本吗

### ISSUE THREAD

**Issue by gaord** [MemFire-Cloud/supabase-wechat-stable-v2#4]
报错：
wefetch.js?t=wechat&s=1720154833025&v=bcedacc96e0e00299404d04817c1dfc1:10 GET https://aibc.com.cn:1273/rest/v1/countries?select=* 404 (Not Found)

还是只适配memfire的版本？

**Comment by iswarezwp** [comment]
原生supabase目前不支持wechat

**Comment by gaord** [comment]
表名写错了。表和存储可以适配supabase官方最新发布。点赞！
